### ISSUE TITLE
Getting this error when trying to run after latest commits

### ISSUE THREAD

**Issue by driftywinds** [amanjha8100/chords#26]
RequestsDependencyWarning: urllib3 (2.0.0.dev0) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "app.py", line 20, in <module>
    bot.run(os.getenv('TOKEN'))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 723, in run
    return future.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by amanjha8100** [comment]
Hey @driftywinds , is ffmpeg , properly configured on your local machine?

**Comment by amanjha8100** [comment]
I did, while I was testing, it got changed!!
